import Providers from "@sc/components/client/Providers"
import Footer from "@sc/components/server/footer"
import Navbar from "@sc/components/server/navbar"
import { tm } from "@sc/libs/util/style/merge"
import { interFont } from "@sc/styles/fonts"

import "@sc/styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={tm(interFont.className, "p-4")}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
