import { interFont } from "@sc/styles/fonts"

import "@sc/styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${interFont.className}`}>{children}</body>
    </html>
  )
}
